pcdshub/lightpath

.landscape.yml
.travis.yml
README.rst
conda-recipe/meta.yaml
docs/source/tutorial.rst
lightpath/controller.py
lightpath/path.py
lightpath/tests/conftest.py
lightpath/tests/test_controller.py
lightpath/tests/test_path.py

Closes #15 
Prior to this commit, the branching logic in the lightpath required that the last device in every beamline be an optic. This however is not the case in actuality. In most cases involving mirrors, there are multiple devices allowed on the "shared" line after the optic but before the pointing has diverged into multiple beamlines. This update allows us to accomodate this within the lightpath as well as handle situations where pointing to different beamlines requires the coordination of multiple upstream optics i.e beam can not be delivered to MFX unless XRT M1H is removed AND XRT M2H is inserted. 
* Removed `pcaspy` from conda-recipe
* Some quick style fixes
* Add landscape cfg and badge

MAINT: Improve branching logic

---

lightpath/tests/test_gui.py
requirements.txt

We should not be installing PyQt5 via pip! This destroyed my miniconda!!

BLD: Remove PyQt5 install to avoid conda / pip conflicts

---

lightpath/controller.py
lightpath/path.py
lightpath/tests/conftest.py
lightpath/tests/test_widgets.py
lightpath/ui/gui.py
lightpath/ui/widgets.py

Closes #23 and closes #26 
EPICS calls are a resource! The`lightpath` shouldn't have blind trust that calls like `inserted` are implemented efficiently for each device. The UI should also be efficient using a single callback from the `BeamPath` object to configure all of the widgets instead of repeated calls. Here are a list of changes
* `Unknown` is now displayed in yellow as not to be confused with `Inserted`. This is the only change to the UI
* All properties in `BeamPath` that make calls to `inserted` internally stash device positions. The idea is we should never be doing something like this which calls `device.inserted` for every device every time the property `inserted_devices` is requested.
```
if self.inserted_devices:
return self.inserted_devices[0]
else:
if self.inserted_devices …
```

MAINT: Use EPICS efficiently

---

lightpath/tests/conftest.py

API update for newest Ophyd compatibility in tests. I tried to change as few lines as possible.

MAINT: name is now a required keyword-only argument.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
lightpath/controller.py
lightpath/path.py
lightpath/tests/test_gui.py
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py

Add a number of nice features to the user interface including:
* Remove buttons will not be displayed for devices that do not have a `remove` method
* Insert buttons are displayed for devices that have an `insert` method
* Instead of using a frame around the device name, the frame of the `LightIndicator` is used to display MPS faults
* A slider at the top of the window to control the `minimum_transmission` considered non-blocking
* A `try` `except` in `BeamPath.blocking_devices` will catch any errors raised while checking `inserted` or `removed` on devices. 
One note, @hhslepicka after https://github.com/slaclab/pydm/pull/164 `pyqtgraph` is now an explicit dependency (If you import `pydm` you need `pyqtgraph`). I know the `PyQt` req stuff can be tricky, but I don't think there is any harm …

ENH: UI Improvements 

---

conda-recipe/meta.yaml
lightpath/path.py
lightpath/tests/conftest.py
requirements.txt

Remove numpy from the dependency tree. Only using it for `np.nan` and `np.inf` which are now included in the `math` module.
Why not?

DEP: No more numpy dependency

---

.travis.yml

Fix Travis bug with Numpy from pip missing openblas library.
The previous fix ( PR #37 ) did not fixed the issue.
Looking at the TravisCI log I noticed that we had duplicated packages showing as `conda` installed and `pip` installed.
Since all the dependencies (except QDarkStyleSheet which is optional) are set at `conda create` there is no need to call `pip install -r requirements.txt` at travis.yml.
This change is required so we can properly build Lightpath.
At my environment & Travis (https://travis-ci.org/hhslepicka/lightpath/jobs/302070533).
In here.

Fix travis #2

---

conda-recipe/meta.yaml

Conda recipe does not correctly specify `happi` version

FIX: Correctly specify happi version

---

MANIFEST.in
setup.py

Add the ui file to the `MANIFEST.in` file, set `include_package_data=True`
This means we can distribute lightpath as a conda package and it will work.
python setup.py build creates the correct file structure

BLD: Build with the ui file

---

.travis.yml
conda-recipe/meta.yaml
examples/demo.py
lightpath/controller.py
lightpath/path.py
lightpath/tests/__init__.py
lightpath/tests/conftest.py
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py
lightpath/ui/gui.py
lightpath/ui/lightapp.ui

This pull request makes `lightpath` work with `happi > 0.5.x` and `pcdsdevices > 0.3.x`. The major changes that affected the lightpath were:
1. Metadata is no longer tacked on to the device. All references to `device.z` had to be changed to `device.md.z`
2. `MPS` devices are no longer associated with devices. They will be in the `happi` database as a separate object
3. All device loading should be done in happi.
For the actual `BeamPath` code, I deprecated all the references to the MPS system. In the future, we will just create a small object `MPSSummary` that manages the entire MPS system for a beamline. These will also be displayed in their own panel in the purpose of the GUI.
The most frustrating change is that the UI used to treat `happi.Device` objects and `pcdsdevices` objects the …

MAINT: Update to latest pcdsdevices, happi

---

examples/demo.py
lightpath/config.py
lightpath/controller.py
lightpath/path.py
lightpath/tests/__init__.py
lightpath/tests/conftest.py
lightpath/tests/path.json
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py
lightpath/ui/gui.py

* Instead of passing already configured devices into `LightController` you pass a `happi.Client`. The `LightController` is then responsible for selecting the correct devices and instantiating them. 
* `LightApp` takes a `LightController` object instead of a list of devices.
* The `LightController` has an optional `endstations` keyword that will only load a list of hutches beampaths. 
* Prior to this PR, the `LightController` used a tangled web of code to stitch together beamlines based on the device it found. This is now hard coded in `lightpath/config`. There is a `beamlines` dictionary where each endstation is a key with a nested dictionary describing the complete path. You can just leave the smaller dictionary blank indicating you want to include the entire beamline, or you can …

API: Controller

---

.gitignore
bin/lightpath
lightpath/tests/test_gui.py
setup.py

Launch script to show GUI for arbitrary `happi` database.
```bash
lightpath --db PATH_TO_DB
```
I hardcoded in the path where it currently lives as a default. I though about importing this from `hutch_python` but adding a dependency for just a single path seems gratuitous. 
Closes #56 
* Added test for script packaging
* Tested with real database

ENH: Launch Script

---

lightpath/path.py
lightpath/tests/conftest.py
lightpath/tests/test_path.py

The `lightpath` wasn't suitably protected against faulty devices. Many of the methods shamelessly called `device.inserted` e.t.c not accepting that these usually involve Channel Access calls that are liable to fail. Now, we only ask for device information in `find_device_state`. This returns a `DeviceState` enum that describes the state. This helps limit the number of Channel Access calls and in turn uniformly handle when these things fail.
Closes #61 
Added a test for a broken device

MAINT: Handle faulty devices

---

.travis.yml
README.rst
dev-requirements.txt
lightpath/tests/test_widgets.py
lightpath/ui/widgets.py

Since the last release of `lightpath` we now summarize the state of every device in a convenient enum `DeviceState`. This change had not made its way up to the UI. Previously we created a custom Enum here by checking `inserted` and `removed`, this is now removed in favor of `find_device_state`.
We were also using a bunch of varying Conda channels we no longer depend on. Updated both `Travis` and the `README` to show the simpler install. Also added `flake8`
Closes #65 
Strengthened existing test

MAINT: DeviceState in UI

---

lightpath/tests/test_widgets.py
lightpath/ui/device.ui
lightpath/ui/gui.py
lightpath/ui/widgets.py

Part of the transformation to making the UI look more like the old system. We now create a mock "drawing" of the beamline that lights up according to the device state and whether the beam is being transmitted or not.

UI: Beamline

---

conda-recipe/meta.yaml
lightpath/tests/test_gui.py
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py
requirements.txt

A bunch of helpful navigation widget options. You can now:
* Force scroll to an arbitrary device
* Force scroll to the most upstream blocking device
* Hide devices that are removed from the beam
* Hide devices based on their class
I also implemented the `upstream` filter in the more general structure now. This means we **only** disconnect / reconnect to widgets when we switch beamlines. Avoid loading the entire beampath whenever possible!
Closes #73 
Closes #67 
Added tests for all new functions

ENH: Filter Options

---

lightpath/tests/test_gui.py
lightpath/ui/device.ui
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py

There is now a widget at the top of the screen that shows a condensed view of the entire beamline. This is to help orient operators where they are in space when looking at the detailed view. To make this even more intuitive I created another slider that shows which swathe of the overview you have open in the detailed view. This can be also dragged around to inspect different portions.
Closes #64 
Modified existing tests to pass, but no new tests were added.

ENH: Beamline Overview

---

.travis.yml
conda-recipe/meta.yaml
examples/demo.py
lightpath/tests/test_gui.py
lightpath/ui/default.ui
lightpath/ui/device.ui
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py
requirements.txt

* The base widget to display a Device just added a generic rectangle and changed its color to reflect the state. In the future, we want to support arbitrary symbols containing multiple different `PyDMDrawing`. This PR creates a new widget that loads `.ui` file then whenever the state changes we adjust the stylesheet of **all** `PyDMDrawing` widgets contained inside it. It also sets up some nice shortcuts like every widget 
* When you click on a `DeviceDrawing` in the overview we show the corresponding `typhon.DeviceDisplay` in the sidebar
* `Miniconda-latest` is now `3.7`. We need to `conda-build` with the `--python` keyword.
* If you `click` a widget in the overview, we focus on it in the beamline drawing.
* `typhon` is a dependency
* Use the `typhon` machinery to load the dark …

ENH: Typhon

---

lightpath/path.py

Correction to make branching logic far easier to specify:
1. Walk beamline remembering the optics that we see
2. When we find a device that is not a new beamline review the optics we've seen. There are two ways a device can be blocking:
* If the optic specifically lists our hutch as a possible destination but it is not presently being delivered there i.e XPP LODCM lists HXD instead of XPP
* If the optic does not list our new beamline as a destination, it must be "passing" beam through along its current path.
Instead of https://github.com/pcdshub/pcdsdevices/pull/291
* Existing tests all pass
* Works on current `lightpath` database

FIX: Modify branching logic to ignore removed optics when suitable

---

lightpath/tests/test_gui.py
lightpath/ui/gui.py
lightpath/ui/widgets.py

There was a bug where multiple hidden conditions would override each other. This behavior was rather unintuitive. For a widget to be visible it should have to meet all the selected criteria not just one. This PR consolidates the hidden logic into a single `filter` function which is then triggered by all the buttons.
Closes #81 
* Modified test suite for new filtering functions
* Added a check for multiple filtering functions being active simultaneously

FIX: Multiple Hidden Conditions

---

conda-recipe/meta.yaml
lightpath/ui/gui.py
lightpath/ui/widgets.py
requirements.txt

Use the `qtpy` abstraction layer for base `PyQt` imports
After https://github.com/slaclab/pydm/pull/380 PyDM now uses `qtpy` as its interface layer. There may be a day in which the `PyDM` interface layer is deprecated. This PR prepares us for this day if and when it should arise. 
Existing test suite

MAINT: Swap to qtpy

---

lightpath/tests/__init__.py
lightpath/tests/conftest.py

Avoid calling fixture outside of tests. A little sloppy, but this was the quick patch to make it all work with minimal changes.

FIX: Do not reuse fixture for external use

---

conda-recipe/meta.yaml
lightpath/ui/widgets.py

We changed the API of `grab_kind` in `typhon`. This now uses the new API.

API: grab_kind changes

---

lightpath/tests/path.json
lightpath/tests/test_controller.py

Happi enforces that `name` must be a valid Python identifier now. I did a sloppy find/replace so that the tests pass again.

MNT: Compat with Latest Happi

---

lightpath/config.py

The new beamline is called LFE. I've added it here.
This is leeched off of in other contexts, like in `hutch-python`...
Makes xpppython load the devices. Maybe doesn't break this repo's test, haven't checked.

MNT: add LFE line to HXR configs

---

conda-recipe/meta.yaml
lightpath/config.py

Add TMO to lightpath config with instructions to include KFE and RIX
KFE devices are part of TMO and RXI's paths
This is also used in hutch python to decide which happi devices to load
dev checkout in tmo/rix hutch pythons

ENH: add TMO and RIX lightpath configs

---

lightpath/__main__.py
lightpath/tests/conftest.py

- Removes hard coded `DEVICE_CONFIG`
- loads a happi client from config by default
- adds an option to run lightpath with the sim database
closes #134 
Also sneaks in this sim option which might be useful later
tests run locally.  interactive testing shows the database getting the right path, but currently the database is not up-to-date.
CLI documentation updated.

ENH: find happi db from config, add sim option

---

docs/source/upcoming_release_notes/142-fix_gui_tests.rst
lightpath/__main__.py
lightpath/config.py
lightpath/controller.py
lightpath/path.py
lightpath/tests/__init__.py
lightpath/tests/conftest.py
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py
lightpath/tests/test_widgets.py
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py

Fixes a slew of issues/errors found while running the gui on the updated happi db.  Individual problems will be documented below.
<details> <summary>Detailed problem documentation</summary>
- **Problem**: on teardown, an immense amount of traceback initiated by EPICS CA contexts being unset.
- **Explanation**: On shutdown, nothing is done to gracefully complete/close any in-progress callbacks.  
- **Fix**: Hooked the closeEvent method to run a clean-up method that destroys all the `lightpath_summary` signals before closing.  (This might be a bit heavy handed, but it worked)
- **Problem**: widget subscriptions still subscribed to the whole device with SUB_STATE.  This resulted in failures of the widget to subscribe to some devices, due to SUB_STATE being missing.
- **Fix**: subscribe to …

Follow-up bug fixes, gui details

---

docs/source/upcoming_release_notes/145-enh_lazy_graphs.rst
lightpath/controller.py
lightpath/errors.py
lightpath/mock_devices.py
lightpath/tests/conftest.py
lightpath/tests/path.json
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py

- Make the facility graph use only database information
- Defer device instantiation until needed (when making BeamPath objects, looking for beam destinations etc)
- Attempt to make a mock device if device instantiation fails initially
- Move simulated devices from test suite into separate module for package-wide use
#143 
#139 part 2.
Test Suite runs, extra smoke test for mocked devices added. 
This PR

ENH: Make device loading lazy, make mock devices available

---

lightpath/path.py
lightpath/ui/gui.py
lightpath/ui/widgets.py

Admittedly a bunch of bug fixes that should have been caught when we changed the subscription schema
- Properly unsubscribes callbacks from the `lightpath_summary` signal, instead of the `BeamPath` object.  
- destroy the lightpath_summary signals in all the widgets, not just the first half
- Creates `LightApp.clear_device_subs()` to unsub `BeamPath._device_moved()` all devices in a BeamPath.
This fixes a bug but I went down too many rabbit holes and forgot to document fully with screenshots.  It definitely helps with subscriptions cleanly though.
Interactively
This PR

FIX: clear subscriptions properly

---

docs/source/upcoming_release_notes/150-gui_icons_and_more.rst
lightpath/mock_devices.py
lightpath/path.py
lightpath/tests/__init__.py
lightpath/tests/conftest.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py
lightpath/tests/test_widgets.py
lightpath/ui/gui.py
lightpath/ui/widgets.py

We're finally getting into the issues from the jira tickets!  Kinda.
- Gives the GUI a title that is not "form"
- Removes sorting of endstations to allow lazy loading of BeamPaths
- Fixes device filter area to match with `isinstance`, and no longer use factory functions from pcdsdevices. 
- closes #144 
- Track cumulative transmission along BeamPath, and mark devices as blocking if they force total transmission below a threshold
- Color the widget based on both the device state and path state.   
- A variety of jira tickets, including [jira1](https://jira.slac.stanford.edu/browse/LCLSECSD-143), [jira2](https://jira.slac.stanford.edu/browse/LCLSPC-135), [jira3](https://jira.slac.stanford.edu/browse/LCLSECSD-748)
Also in a more minor sense
- Fixes test suite fa4 deprecation warnings
- …

GUI: More expressive widget icon colors, and more along the way

---

docs/source/upcoming_release_notes/157-perf_no_hinted_signals.rst
lightpath/main.py
lightpath/tests/test_widgets.py
lightpath/ui/device.ui
lightpath/ui/widgets.py

- Removes hinted signals from lightrow widgets for performance reasons
- Removes cli check requiring one of `db` or `hutches`, defaulting to all the hutches in the default config
- Removes the `command` layout, allowing device widget centering
- ?Fixes? tests. Callbacks are being weird, nothing was changed within this PR that should have affected the stylesheet test, but the command hint test was rightfully removed.
In the quest for a faster lightpath, we found that walking and creating the signal widgets on the main screen incurred a significant time loss.  The detailed screens still exist for allowing users to control their devices from lightpath.
As measured from the command line (`time python -m lightpath --hutches XCS`)
Before this PR: ~90s 
After this PR: ~30s 
This also lets us …

PERF: remove hinted signals from LightRow widgets

---

docs/source/upcoming_release_notes/162-gui_loading_screen.rst
lightpath/ui/gui.py
lightpath/ui/lightapp.ui
lightpath/ui/widgets.py

- adds a simple splash screen that pops up during `change_path_display()` calls, closing #82 
- adds a refresh button, closing #159 
- hopefully fixes clipping in overview slider with condensed lightrow widgets, closing #136 
Linked issues above.  The splash screen was shamelessly copied and modified from lucid.
I'm looking into also possibly making the detailed screen width adjustable, since it takes up a lot of room as is.  But that's for tomorrow possibly.
Both sim and real-device lightpaths have been clicked around.  
This PR text

GUI: add loading screen and refresh button

---

lightpath/controller.py
lightpath/path.py
lightpath/tests/test_controller.py

`LightController.load_beamlines` was mistakenly still referencing the built-in `beamlines` config/dictionary, despite the config being updated at `__init__`.  
https://github.com/pcdshub/lightpath/blob/09be87d335952d39a597f2fe8bb1576bd8f2ece3/lightpath/controller.py#L147
This did not show up as a bug because subsequent paths to `LightController.get_paths` did this correctly, and as long as the graph was initialized (using `load_beamlines`) to have the required paths, `get_paths` would find the path and split it according to the new (provided) cfg
https://github.com/pcdshub/lightpath/blob/09be87d335952d39a597f2fe8bb1576bd8f2ece3/lightpath/controller.py#L192
https://github.com/pcdshub/lightpath/blob/09be87d335952d39a597f2fe8bb1576bd8f2ece3/lightpath/controller.py#L212
Where the bug appears …

BUG: read the updated configuration when calling load_beamlines

---

.pre-commit-config.yaml
docs/source/upcoming_release_notes/170-maint_auto_fix_precommit.rst

PR generated from script to fix .pre-commit-config.yaml in all repos, switching out the missing flake8 gitlab mirror for github.

MAINT: scripted fix for precommit

---

conda-recipe/meta.yaml
docs/source/upcoming_release_notes/173-bld_rm_pcdsdev_dep.rst
lightpath/main.py
lightpath/mock_devices.py
lightpath/tests/test_cli.py
lightpath/tests/test_controller.py
requirements.txt

Vendor `AggregateSignal` from `pcdsdevices` to remove pcdsdevices build dependency
We should remove circular dependencies
Issues encountered while playing test-suite-whackamole:
- ophyd cleanup via `ophyd.cl.dispatcher.stop()` seemed to break later tests, which do not restore this cl.  There was error spam that led to its initial inclusion, but removing the no-arg test fixes that (I think)
- the no-arg test would try to pull a HAPPI_CFG, which doesn't exist in CI and is functionality possibly better tested in happi than lightpath
- locally, many intermittent failures were fixed by the inclusion of `time.sleep` calls after changing signals, presumably to allow callbacks to process and `LightApp` to update.  These delays were arbitrary and the test suite passed here, so I haven't included …

BLD: vendor AggregateSignal

---

conda-recipe/meta.yaml
docs/source/upcoming_release_notes/176-mnt_split_xpp.rst
lightpath/config.py
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py
lightpath/ui/gui.py

Splits XPP's single entry in the default config into two: `XPP_MONO` and `XPP_PINK`.  
Fixes the test suite accordingly
Fixes a small bug on the way that didn't re-filter the visible devices after changing a path.
All caps because of some `string.upper()` stuff we do in the GUI.
Previously XPP would have two possible beampaths splitting at the xpp lodcm.  One going on the L0 branch and one on the L2 branch.  While before we were letting lightpath choose which branch is active (by whichever branch has the sees beam at the highest z), it became clear that XPP would want to see the status of either line independently.  
The test_path/test_callback test failed again, but passed after a re-run. I tried adding in a sleep clause to possibly let it process, but the failures are intermittent …

MNT: split XPP into XPP-PINK and XPP-MONO

---

docs/source/upcoming_release_notes/176-mnt_split_xpp.rst
lightpath/config.py
lightpath/tests/test_controller.py
lightpath/tests/test_gui.py

reverts the config split of XPP into two lines for hutch-python compatibility
Hutch-python expects very specific hutch names, so we should not change the ones that are available by default. 
This split can simply be done via custom config files in the future
Can't just revert the whole PR since there were other fixes in it
reverting and running the test suite
This PR

REV: revert split of xpp line

---

conda-recipe/meta.yaml
requirements.txt

Try releasing the pyqt pin
Maybe this fixes our matplotlib py3.11 issues?
may CI be graceful to us
This PR

BLD: release pyqt pin

---

lightpath/tests/conftest.py
lightpath/tests/test_gui.py
lightpath/tests/test_path.py
lightpath/tests/test_widgets.py

Try to fix tests in #169.  Changes like these could be spread in many places
Basically just assert things with a timeout to give conditions the ability to settle.
#169 , and other tests
Locally, and by hitting the GHA re-run button a bunch of times, likely
This PR.

TST: wait for conditions during troublesome tests

---

docs/source/upcoming_release_notes/188-mnt_malformed_device_handling.rst
lightpath/controller.py

- Remove hard failure when branches aren't specified for a lightpath-active (lightpath=true) device.  Instead, we just ignore the device.
- Trim beamline device lists before BeamPath creation.  This allows a user to grab an accurate beam path without instantiating the devices. (as in hutch-python)
- BeamPath.split() is thus now no longer used, but is likely a useful method for later use
[jira (soft fail on invalid device)](https://jira.slac.stanford.edu/browse/ECS-4982)
[jira (lazy trim)](https://jira.slac.stanford.edu/browse/ECS-5048)
interactively, with test suite.  
(Testing with xpppython now)
This PR, jira ticket

MNT: skip processing device if branches are not specified

---

conda-recipe/meta.yaml
gui-requirements.txt
pyproject.toml
requirements.txt

Separates lightpath base and gui-related dependencies
- pip: `lightpath` and `lightpath[gui]`
- ~conda: `lightpath-base` and `lightpath` (includes gui)~  I could not get conda builds working, we leave this split to the conda feedstock
Lightpath keeps dragging qt dependencies along with it
pip installs locally.  Conda eventually, but let's see if CI takes
This PR

BLD: separate lightpath and lightpath[gui] subpackages

---

docs/source/upcoming_release_notes/191-enh_add_generic_rix.rst
lightpath/config.py
lightpath/tests/test_controller.py

Add a "RIX" beamline config that spans K1 and K2, as a counterpart for the CRIX and QRIX configs.
This is a rix3 hutch-python hotfix verbatim as part of https://jira.slac.stanford.edu/browse/ECS-6333
The point is so that there is a beamline called "RIX" to search for devices on when loading hutch-python.
This beamline ends up having all of the shared RIX devices.
Possibly in the future this would be removed if the rix3 hutch-python was split into crix3 and qrix3 but the way all of this works is unclear to me.
Interactively in rix3 for a year+
Here only.

ENH: add generic rix beamline config

---

docs/source/upcoming_release_notes/193-tst_no_flaky.rst
lightpath/tests/test_gui.py
lightpath/tests/test_widgets.py

- This test was actually incorrect, to the best of my understanding.  Previously we inserted a fully-blocking valve upstream of a partially blocking ipimb, then asserted that the ipimb would be half-removed.  The lightpath logic actually expects this to be removed, and this only ever passed because it wasn't getting updated after the upstream valve was inserted.
- In the lightpath app we actually don't have proper callbacks for updating devices that aren't being inserted/removed.  Was it always this way? 🤷 
- looking at sim lightpath, imager (transmission=0.5, not blocking) after sequence of 
- insert upstream blocker  -> insert im -> remove upstream blocker 
- insert im, with all other devices removed
- after way too many print statements, we were moving on before the value of the …

TST: Work to de-flake tests
