.travis.yml, requirements.txt
=> BLD: Returning py34 dependency and installing pcaspy with pip for latest version

.travis.yml, conda-recipe/meta.yaml, requirements.txt
=> FIX: Adding prettytable as a dependency

setup.py
=> FIX: Install dependencies with setup.py

.travis.yml, README.rst, conda-recipe/meta.yaml
Still missing pydm but this will be solved soon.
=> CI: Building conda package properly.

examples/demo.py, lightpath/ui/gui.py
This allows a user to select whether or not they want the dark stylesheet. Placed it as an import within a `try` / `except` just in case it gets left out of the environment.
=> ENH: Add `dark` keyword to UI

.travis.yml, conda-recipe/meta.yaml, requirements.txt
Do not restrict ophyd version
Part of the update of pcds-devices to `ophyd=1.0.0`
Tests are unchanged.
=> BLD: Do not restrict ophyd version

.travis.yml
CI: include channels needed for pydm
CI: include channels needed for pydm
conda build
CI: include channels needed for pydm
=> CI: include channels needed for pydm

.travis.yml, conda-recipe/meta.yaml, lightpath/tests/conftest.py, lightpath/tests/test_gui.py, lightpath/tests/test_widgets.py, requirements.txt
There maybe be non backwards compatible changes in the happi directory soon. I locked the version number down until these are done.
Trying to avoid accidentally breaking things
Tested via Travis. Using the tagged happi build should be no different than using the current master
=> CI: Use fixed happi version

conda-recipe/meta.yaml
Correctly specify happi version
=> FIX: Correctly specify happi version

conda-recipe/meta.yaml
Specify happi version correctly
=> FIX: Specify correctly version happi

.travis.yml, dev-requirements.txt, requirements.txt
Install `lightpath` using its own conda-recipe
**This is the last build of `lightpath` that will be available on `skywalker-dev`. After this it will be built on `pcds-tag`**
Closes #48
=> Travis by Conda

bin/lightpath, conda-recipe/meta.yaml, requirements.txt
The launcher for the `lightpath` UI was fairly bare-bones. This adds:
* `coloredlogs`
* Option to display `DEBUG` messages
* Option to only load a fixed number of beamlines
Closes #68 
Launched with all available options
Added "help" to `argparse` options
=> ENH: Improvements to Launcher

bin/lightpath
Needed to stretch my legs with a real easy PR today. Added the `--version` option to the `lightpath` startup script. Useful to tell where and which `lightpath` module you'll be using when you enter the command.
@hhslepicka
=> ENH: Add version command to lightpath

.travis.yml
* Both `3.6` builds were trying to upload to `CONDA`
* Add `3.7` as we near closer to the day that we are ready to swap.
=> CI: 3.7 and duplicate builds

.travis.yml, conda-recipe/meta.yaml, lightpath/tests/test_gui.py, lightpath/ui/gui.py, lightpath/ui/widgets.py, requirements.txt
Make it work with newest Typhos (renamed Typhon).
=> MNT: Typhos

conda-recipe/meta.yaml, lightpath/controller.py
We're generalizing and cleaning up `happi`, so some API is changing. This adjusts `lightpath` for it.
Tested locally with dev builds until a release
attn @klauer @hhslepicka
=> MNT: happi API changes

.travis.yml, conda-recipe/meta.yaml, lightpath/ui/widgets.py
Fix for newest APIs
Build is broke
Tests pass now
=> MNT: Update for Typhos API

.gitignore, bin/lightpath, lightpath/controller.py, lightpath/tests/path.json, lightpath/ui/widgets.py
Accumulated small fixes PR for lightpath redeployment
closes #112 
closes #114 
partially addresses #116 probably
=> MNT: Fixes for new deployment

.travis.yml, conda-recipe/meta.yaml
- make recipe noarch
- use shared travis config
- enable python>=3.8
- related to https://github.com/pcdshub/pcds-envs/pull/158#issuecomment-758859276
=> MNT: noarch, shared travis config

.travis.yml, MANIFEST.in, requirements.txt, setup.py
=> BLD/FIX: fix PyPI install, requirements, and setup.py

dev-requirements.txt, docs/source/releases.rst
Quick bugfix tag
get a bugfix out before the new env?
`make html` ran without issue
This is documentation yay
=> DOC: release notes for v1.0.1
